### ISSUE TITLE
Looking forward to the Gradio demo code

### ISSUE THREAD

**Issue by north151** [AlonzoLeeeooo/StableV2V#1]

**Comment by AlonzoLeeeooo** [comment]
Hi @north151 , hope this message finds you well! We are thrilled to notice you that we have updated the Gradio demo in [this commit](https://github.com/AlonzoLeeeooo/StableV2V/commit/121ee7e30d641430ea2ae53316f450840227aa4c). You may start trying the demo by referring to the detailed instructions in [the corresponding section](https://github.com/AlonzoLeeeooo/StableV2V?tab=readme-ov-file#inference-of-stablev2v-gradio-demo) in our README document.
