### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by lyzcool** [AlonzoLeeeooo/StableV2V#10]
Hello author, may I ask how much memory is needed to run the code? My 48GB A6000 does not have enough memory.

**Comment by AlonzoLeeeooo** [comment]
Hi @lyzcool ,

We recommend you use at least A100 GPU for inference purpose. Meanwhile, we are currently looking for potential solutions to reduce the memory requirement, and will update the codebase if we find any in near future.

Also, please note that the current codebase does not support `xformers`, which will somehow cause artifacts in the generated video. There might be some incompatibility between the code and the one of `xformers`. We will also fix this if possible.

For more details, please refer to this similar issue #7 . If you any further questions, please do not hesitate to contact us again.

Best regards,
Chang
