### ISSUE TITLE
conda environment

### ISSUE THREAD

**Issue by tyrink** [AlonzoLeeeooo/StableV2V#3]
Could you please provide the guidelines to establish the conda environment?

**Comment by AlonzoLeeeooo** [comment]
Hi @tyrink ,

Thanks for your attention of our work! I have just updated a configuration file in [this commit](), which enables you to install the dependencies with `conda`.

Specifically, you can execute the following command line for installation:
```bash
conda create -f environment.yaml
```
Then, you are ready to go with `conda activate stablev2v`. Feel free to leave further messages if you have other questions.

Best regards,
Chang

**Comment by tyrink** [comment]
Thanks for your prompt response!

**Comment by AlonzoLeeeooo** [comment]
> Thanks for your prompt response!

You're welcome!

**Comment by tyrink** [comment]
By the way, is there any idea to deal with the mismatched mask tensor shape?
![image](https://github.com/user-attachments/assets/fba9e6f7-c2df-498c-b2a5-45c7a194a1df)

**Comment by AlonzoLeeeooo** [comment]
> By the way, is there any idea to deal with the mismatched mask tensor shape? ![image](https://private-user-images.githubusercontent.com/75239935/388420733-fba9e6f7-c2df-498c-b2a5-45c7a194a1df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDA3NzIsIm5iZiI6MTczMjIwMDQ3MiwicGF0aCI6Ii83NTIzOTkzNS8zODg0MjA3MzMtZmJhOWU2ZjctYzJkZi00OThjLWIyYTUtNDVjN2ExOTRhMWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE0NDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlM2IyNWZkNDkyZTY3ZmZmNzI1MmNhN2Y1YTEzMmM0YWM2NWM1YjgxOWM5NTlmZjdjOTdmMzUxODA3OWE0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dUXLpIsPARFMGqos8_GnkDePDn34Wy_Z-EQ94YUpLuw)

@tyrink Thanks for pointing this out! This is an error caused by the our implementation in older versions. It should be fixed now after [the latest commit](https://github.com/AlonzoLeeeooo/StableV2V/commit/f2b4cc0fa2e4dd774ed902bc15dd42efbd8743b1). Please try it again. Feel free to let us know if the error proceeds or there is any other problems.
