### ISSUE TITLE
[Fixed error when loading non-RGB images] RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[2, 4, 512, 512] to have 3 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by north151** [AlonzoLeeeooo/StableV2V#4]
When I run app.py，RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[2, 4, 512, 512] to have 3 channels, but got 4 channels instead

**Comment by AlonzoLeeeooo** [comment]
> When I run app.py，RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[2, 4, 512, 512] to have 3 channels, but got 4 channels instead

Hi @north151, 

mai I kindly ask what specific image editor type you used?

**Comment by AlonzoLeeeooo** [comment]
> Thank you. I've taken care of that

Great to hear that! Feel free to let me know if there is other problems. We will handle your other issues later.

**Comment by rayryeng** [comment]
I am getting the same bug. Can you please describe what was done to solve this? I used the `paint-by-example` image editor.

**Comment by AlonzoLeeeooo** [comment]
> I am getting the same bug. Can you please describe what was done to solve this? I used the `paint-by-example` image editor.

Hi @rayryeng ,

Would you please offer more details such as the inputs and the reference image? So that I can try reproducing the error on my ends. Thanks!

**Comment by rayryeng** [comment]
Thanks so much for your reply. I'm using 49 frames of an object that is rotating 360 degrees with a static background. The reference image is one frame from this sequence.

I have both 720 x 480 and 1024 x 1024 versions of this sequence using `paint-by-example`.

**Comment by AlonzoLeeeooo** [comment]
Great! Looking forward to it :)

**Comment by rayryeng** [comment]
Hello @AlonzoLeeeooo Thank you for your patience. Please see this ZIP file from my Google Drive: https://drive.google.com/file/d/1_NEFAG_aLyJtZIdDwEl8ZLXJYGgDW3Mx/view?usp=sharing

It has two directories - one that is formatted with the frame sequence at 720 x 480, and another at 1024 x 1024 in case the network requires square images. I used the Gradio app to put all of the frames as the input video sequence, then selected the first frame of these as the example. I tried both resolutions and I got the bug seen above. The prompt is simply `Cat in leather jacket` and I've left all of the default hyperparameters alone.

**Comment by AlonzoLeeeooo** [comment]
Hi @rayryeng ,

The problem should now be fixed in [this commit](https://github.com/AlonzoLeeeooo/StableV2V/commit/3acfe90d5f4020afab3ff1b5151c1ed2ea570c32). This error is caused by loading non-RGB images (e.g., RGBD images with 4 channels) with `PIL.Image.open()` without `.convert("RGB")`.

Specifically in `runners/iterative_warping/run_flow_extraction.py`, the previous implementation is:
```python
img = np.array(Image.open(imfile)).astype(np.uint8)
```
Currently it is modified into:
```python
img = np.array(Image.open(imfile).convert('RGB')).astype(np.uint8)
```
where `.convert('RGB')` makes sure that the code loads 3-channel images.

We will pin this issue as it is important when editing non-RGB images. Please do not hesitate to contact us again if you have any further questions.

Best regards

**Comment by rayryeng** [comment]
Thank you very much for the quick response. I should have known that seeing that there were 4 channels xD. I will test this. In the meanwhile, I've discovered another bug, but I've opened a PR that can be merged when you're ready. Thank you again for your great work!

**Comment by AlonzoLeeeooo** [comment]
> Thank you very much for the quick response. I should have known that seeing that there were 4 channels xD. I will test this. In the meanwhile, I've discovered another bug, but I've opened a PR that can be merged when you're ready. Thank you again for your great work!

Thanks for your efforts. We appreciate it. The PR is merged now.
