### ISSUE TITLE
AttributeError: 'ArgumentParser' object has no attribute 'xformers'

### ISSUE THREAD

**Issue by north151** [AlonzoLeeeooo/StableV2V#6]
StableV2V/runners/i2vgenxl_ctrl_adapter_inference_runner.py", line 101, in i2vgenxl_ctrl_adapter_inference_runner
    if args.xformers:
AttributeError: 'ArgumentParser' object has no attribute 'xformers'

I succeeded by commenting the code

    # if args.xformers:
    #     pipe.enable_xformers_memory_efficient_attention()

**Comment by AlonzoLeeeooo** [comment]
Hi @north151 ,

Thanks so much for your suggestions! I have remove the lines in [this commit](https://github.com/AlonzoLeeeooo/StableV2V/commit/131e6b7c8b72c64f87c3149e5a40257bb5707f92). It should work in the current version.

Please note that `StableV2V` does not support `xformers`, unfortunately. According to our previous experiments, turning on `xformers` causes severe artifacts in the generated video, where there might exist some incompatibility in the current codebase and the implementation of `xformers`. We would pay attention to this issue and fix it in the future if possible.
